### ISSUE TITLE
Opinion: Enabling all plugins by default

### ISSUE THREAD

**Issue by hackorum** [VapourNvim/VapourNvim#28]
Feel free to share your opinion on enabling all the plugins by default on install here. I personally feel that everything should be enabled by default, then the user can disable plugins that they don't need in the config file. What are your thoughts on this? Should everything be enabled by default or not?

**Comment by KarolusD** [comment]
It will be definitely more beginner friendly to have them turn on out of the gate (not sure about language servers as they might differ depending on the user - maybe console can ask about each of them when installing i.e "Do you want to install bash language server? (y/n)" etc.)
