### ISSUE TITLE
Running `nvim .` or `nvim File_Name` causes error and crashes

### ISSUE THREAD

**Issue by iktefish** [VapourNvim/VapourNvim#35]
I'm using Fish, running `nvim .` to open a directory throws this error with Neovim quitting right after:
```
Error executing luv callback:
...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: vim.lua:63: cannot open /home/vale/.config/nv
im/lua/plenary/async/util.lua: No such file or directory
Press ENTER or type command to continuefish: Job 1, 'nvim main.rs' terminated by signal SIGABRT (Abort)
```

Also trying to open a file using `nvim File_Name` throws this error with Neovim quitting right after:
```
fish: Job 1, 'nvim main.rs' terminated by signal SIGABRT (Abort)
```

If I just run `nvim` and find my file using Telescope, fine opens without errors and experience no crashes.

**Comment by hackorum** [comment]
If not then adding `Vapour.plugins.neogit.enabled = false` and then restarting and `:PackerSync` should fix the problem.

**Comment by hackorum** [comment]
Does the same thing happen if you are using zsh?

**Comment by iktefish** [comment]
I realized the core dump occurs when a proper executable isn't found in the path specified for the ` lua-language-server `.
