### ISSUE TITLE
Theming suggestion: Catppuccin - mid-tone dark theme

### ISSUE THREAD

**Issue by Pocco81** [VapourNvim/VapourNvim#39]
Hey mate! I've been peeking around the repo ever since you first announced the config. It's really awesome, great work! 

With that said, I was wondering if you wanted to "team up" in some way. I'm working on this colorscheme called [Catppuccin](https://github.com/catppuccin) (I'll be releasing it officially between today or tomorrow). 

<p align="center">
  <img src="https://raw.githubusercontent.com/catppuccin/catppuccin/dev/assets/misc/sample.png"/>
</p> 

I was needing some screenshots to showcase the Nvim port of the theme, but my rice isn't the prettiest one IMHO. After looking at your latest post on r/unixporn I had the idea to ask you if you would like to help me taking promo screenshots, and in exchange Vapour will appear on the README.  The theme is really good (very biased, I know)!

Catppuccin is a community-driven mid-tone dark theme that aims to be the middle ground between low and high contrast themes, providing a warm color palette with 16 eye-candy colors that are bright enough to be visible during the day, yet pale enough to be easy on your eyes throughout the night. You can read more about its design philosophy [here](https://github.com/catppuccin/catppuccin/tree/dev#-design-philosophy). 

Try it out! Who knows? Maybe you'll end up liking it so much that it will become Vapours official theme?

**Comment by hackorum** [comment]
Hi @Pocco81, I'm glad you liked the project. I really appreciate it :)
I would love to team up or collaborate with you on this colorscheme!

I really like the colors of this theme but there is very less contrast in lualine. I have made an issue for that in your `catppuccin/nvim` repo. And I also suggest you to change the name of the colorscheme to **Yakuatte** because there is another colorscheme for neovim called catpuccino (I have seen the github issue).

I have also taken some screenshots of my rice with catpuccino. I did not change the wallpaper or the bar because your colorscheme looks pretty similar to rosé pine and the wallpaper looks good with the theme.

These are the screenshots:

![Screenshot 2021-11-13 at 9 32 59 AM](https://user-images.githubusercontent.com/70092545/141605351-bf70fe89-8740-4a12-b1a4-3afc6ae24fc1.png)

![Screenshot 2021-11-13 at 9 32 12 AM](https://user-images.githubusercontent.com/70092545/141605357-5bceb193-9d2a-4286-9973-28c505bbf38e.png)

![Screenshot 2021-11-13 at 9 35 43 AM](https://user-images.githubusercontent.com/70092545/141605361-754018b5-4980-4073-a87e-2214c62ca019.png)

I hope you liked the rice :D

**Comment by Pocco81** [comment]
> I really like the colors of this theme but there is very less contrast in lualine. I have made an issue for that in your catppuccin/nvim repo.

Just replied ;)

> And I also suggest you to change the name of the colorscheme to Yakuatte because there is another colorscheme for neovim called catpuccino (I have seen the github issue).

Ahmm actually the reason for changing the name was because there is this inactive user with the name @Catppuccino, not because there is another theme names Catppuccino (at least none that I know of). The original name of this project was Catppuccino :)

> I did not change the wallpaper or the bar because your colorscheme looks pretty similar to rosé pine.

Not really... starting from the fact that rose pine doesn't have Fuchsia, orange or green, which Catppuccin does LOL. Here is a side by side comparison of the main colors (the black spaces are because those colors are missing):
### Catppuccin
![image](https://user-images.githubusercontent.com/58336662/141605794-5d5699d6-6375-4df4-a955-a6d3ee7557ec.png)

### Rose
![image](https://user-images.githubusercontent.com/58336662/141605800-5b7e7c7f-ae68-4600-8b6d-66e9b2c54c8c.png)

Briefly, Rose Pine is paler, whereas Catppuccin's got more contrast. The main colors are different too: Catppuccin's main colors are pink, magenta and fuchsia, Rose pine's got green, blue and purple :)

That's why I asked you if you were willing to team up, because I know ricing your desktop and changing the colors takes... time.

> I hope you liked the rice :D

I really liked, indeed! but I can't add it because the colors and the wallpaper are not from Catppuccin. Would it be possible for you to retake the SSs but with Catppuccin only? If not then it's fine to, I appreciate your effort; I could try to pull something off with Photopea lol.

**Comment by hackorum** [comment]
> Ahmm actually the reason for changing the name was because there is this inactive user with the name @Catppuccino, not because there is another theme named Catppuccino (at least none that I know of). The original name of this project was Catppuccino btw :)

Oh I thought catppuccino was a different colorscheme. I had tried it once when you posted it on reddit but I removed it because I couldn't get lualine to work that time.
> Not really... starting from the fact that rose pine doesn't have colors like fuchsia, orange or green, which Catppuccin does LOL. Here is a side by side comparison of the main colors (the black spaces are because those colors are missing):

Ahhh I see

> I can't add there screenshots because the colors and the wallpaper are not from Catppuccin. Would it be possible for you to retake the SSs but with Catppuccin only?

Yes I can definitely do that. MacOS has a feature in which we can capture only the selected window and nothing else. It also gives a beautiful shadow to the screenshot. I'll send some screenshots after sometime. Is it ok for you?

**Comment by Pocco81** [comment]
I agree with everything you just said. Take your time, no hurry!

If it helps, these are the colors I used for making the navbar for Tmux:

![image](https://user-images.githubusercontent.com/58336662/141606388-a5f631c0-00b6-46f4-8d9f-079540c01b4c.png)

I haven't had time (again, yes, lol) to standardize which colors serve which specific function, so feel free to implement them as you want :+1:

You can view the colors more easily here:

+ Main colors: https://coolors.co/f0f0f5-ea31b5-ae9ad6-f0a8e4-e28d8d-e7a988-add692-f0dc89
+ UI dev colors: https://coolors.co/0e0c13-1b1624-221e2f-312c44-3e4058-6f6a8a-84a5cb-b9c4e3

**Comment by hackorum** [comment]
I converted an existing wallpaper that I had to the catppuccin color palette and I have taken some screenshots:
![Screenshot 2021-11-13 at 12 57 39 PM](https://user-images.githubusercontent.com/70092545/141610362-b76ab1e6-6bb9-4a8e-ba13-a7b2d8e4328d.png)

![Screenshot 2021-11-13 at 12 57 54 PM](https://user-images.githubusercontent.com/70092545/141610374-c67f8c99-997a-4cb7-81b6-8fb1e781355a.png)
![Screenshot 2021-11-13 at 1 03 44 PM](https://user-images.githubusercontent.com/70092545/141610426-fc0437c4-dc1c-4574-8e76-664699327814.png)

**Comment by Pocco81** [comment]
Awesome! I'll add those. Two questions tho:

1. What terminal emulator are you using?
2. Would it be possible to port Catppuccin to yabai? Sorry I don't use Mac :)

**Comment by hackorum** [comment]
> What terminal emulator are you using?

I am using alacritty

> Would it be possible to port Catppuccin to yabai? Sorry I don't use Mac :)

Yabai doesn't have any colorschemes but the only place where colors are used is the window borders which don't work right now. So, you don't need to port it to yabai.

> Your neofetch rice looks very tasty too, where can I find it?

It is in my [dotfiles](https://github.com/hackorum/.dotfiles)

And as you asked, here is the screenshot:

![Screenshot 2021-11-14 at 11 02 42 AM](https://user-images.githubusercontent.com/70092545/141669040-713969b6-5c12-4cda-9380-d4f70d5b7d0f.png)

**Comment by hackorum** [comment]
Same screenshot but with a bigger window:
![Screenshot 2021-11-14 at 11 09 19 AM](https://user-images.githubusercontent.com/70092545/141669081-3b8d4946-a75c-4053-aebe-0490534e0779.png)

**Comment by hackorum** [comment]
I have added catppuccin to VapourNvim. You can set it by adding `Vapour.settings.colorscheme = 'catppuccin'` in `~/.config/nvim/lua/vapour/user-config/init.lua` which can be opened easily by pressing space+E. Thanks for the awesome colorscheme 💯

**Comment by toonvank** [comment]
> Hi @pocco81, I'm glad you liked the project. I really appreciate it :) I would love to team up or collaborate with you on this colorscheme!
> 
> I really like the colors of this theme but there is very less contrast in lualine. I have made an issue for that in your `catppuccin/nvim` repo. And I also suggest you to change the name of the colorscheme to **Yakuatte** because there is another colorscheme for neovim called catpuccino (I have seen the github issue).
> 
> I have also taken some screenshots of my rice with catpuccino. I did not change the wallpaper or the bar because your colorscheme looks pretty similar to rosé pine and the wallpaper looks good with the theme.
> 
> These are the screenshots:
> 
> ![Screenshot 2021-11-13 at 9 32 59 AM](https://user-images.githubusercontent.com/70092545/141605351-bf70fe89-8740-4a12-b1a4-3afc6ae24fc1.png)
> 
> ![Screenshot 2021-11-13 at 9 32 12 AM](https://user-images.githubusercontent.com/70092545/141605357-5bceb193-9d2a-4286-9973-28c505bbf38e.png)
> 
> ![Screenshot 2021-11-13 at 9 35 43 AM](https://user-images.githubusercontent.com/70092545/141605361-754018b5-4980-4073-a87e-2214c62ca019.png)
> 
> I hope you liked the rice :D

Hey what is this wallpaper. I really like it! Great rice btw!
