### ISSUE TITLE
Error on "nvim + Hop"

### ISSUE THREAD

**Issue by galexbh** [VapourNvim/VapourNvim#40]
I get this error when using the shortcut 's'.

![image](https://user-images.githubusercontent.com/37647434/141695902-69054d9b-0e08-487d-abdf-455be40aadcf.png)

**Comment by hackorum** [comment]
Yesterday I had removed a few of the plugins and hop is one of them. You need to pull the changes. But you can still install it by adding:
`Vapour.plugins.user = {{phaazon/hop.nvim}}` and then add the keybindings:
```lua
vim.api.nvim_set_keymap('n', 's', ":HopChar2<CR>", {silent = true})
vim.api.nvim_set_keymap('n', 'S', ":HopWord<CR>", {silent = true})
```
