### ISSUE TITLE
Permission Deny while using Terminal in VapourNvim

### ISSUE THREAD

**Issue by Augists** [VapourNvim/VapourNvim#41]
I could not create any file in vapournvim's terminal
For example
`<space> T f` to open a floating terminal
then `touch temp.txt` will get an error `touch: temp.txt: Permission denied`
So, how to fix it? Thx

**Comment by hackorum** [comment]
Try using sudo. Or you can just create a new file from nvim tree or the e command

**Comment by Augists** [comment]
> Try using sudo. Or you can just create a new file from nvim tree or the e command

I mean I cannot try command like
'go run test.go > test.html'
sudo doesn't work fine😭

**Comment by hackorum** [comment]
then try with default terminal `:term` or `:terminal`

**Comment by Augists** [comment]
lol
fine thx
