### ISSUE TITLE
Bug: onedark color scheme

### ISSUE THREAD

**Issue by galexbh** [VapourNvim/VapourNvim#44]
I have made the pull request to the latest version, when changing the color scheme of init.lua with 'onedark' the following appears:

![image](https://user-images.githubusercontent.com/37647434/144536208-33c219f7-71a5-471c-9f62-f5a2f0326c16.png)

![image](https://user-images.githubusercontent.com/37647434/144536341-9e6abb78-8cea-43a4-b583-a6be9f7c65a4.png)

I have tested all the schemes but this is the only one I have problems with.

![image](https://user-images.githubusercontent.com/37647434/144536776-dd81e3b4-dfa7-4b2f-a8bd-ebb3b297e48e.png)

![image](https://user-images.githubusercontent.com/37647434/144536815-90314de6-2ae5-4290-b221-1a6934142d3d.png)

**Comment by hackorum** [comment]
Don't do that, add `Vapour.settings.colorscheme = 'onedark'` in your config file which can be opened by pressing space+E

**Comment by hackorum** [comment]
I have fixed the issue, you can do `git pull`
