### ISSUE TITLE
how to add a new language server not in the preconfigured language list

### ISSUE THREAD

**Issue by SongTianxian9** [VapourNvim/VapourNvim#45]
As above, thanks

**Comment by hackorum** [comment]
Which language server do you want to use?

**Comment by SongTianxian9** [comment]
> Which language server do you want to use?

I am still a student, so I will be exposed to many languages, **clangd, rust_analyzer,  ocaml-lsp** or some others. So I hope I can understand how can  add language that I want to touch

**Comment by hackorum** [comment]
You can get custom language servers by adding:
```lua
Vapour.language_servers.clangd = { enabled = true }
```

**Comment by Rakshith-SS** [comment]
Can't you add [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer/) to VapourNvim so that a user could install the language servers that they particularly need?

**Comment by hackorum** [comment]
Ok, I'll see

**Comment by hackorum** [comment]
I have added nvim-lsp-installer to vapournvim. Now you can just install language servers with :LspInstall

**Comment by Rakshith-SS** [comment]
Great
