### ISSUE TITLE
Failed to install uga-rosa/cmp-dictionary

### ISSUE THREAD

**Issue by galexbh** [VapourNvim/VapourNvim#46]
![image](https://user-images.githubusercontent.com/37647434/146862576-455d73da-7172-406c-985f-e4daaeb3a2d2.png)

after
lua/vapour/plugins/init.lua
use {'uga-rosa/cmp-dictionary', after = "nvim-cmp", disable = not is_enabled('cmp')}

before
use {'uga-rosa/cmp-dictionary', disable = not is_enabled('cmp')}

**Comment by hackorum** [comment]
Just press q then restart neovim and everything should work fine

**Comment by galexbh** [comment]
When creating the dict/words folder the error disappears.

`sudo mkdir /usr/share/dict/words `
