### ISSUE TITLE
add feature: vim-fugitive

### ISSUE THREAD

**Issue by julianobarbosa** [VapourNvim/VapourNvim#52]
please is possible add [vim-fugitve](https://github.com/tpope/vim-fugitive).

https://github.com/tpope/vim-fugitive

**Comment by hackorum** [comment]
As I have already added neogit and lazygit to vapournvim, I have not added this plugin. But you can install it by adding this to your `~/.config/nvim/lua/vapour/user-config/init.lua` which can also be opened by pressing `space+E`:
```lua
Vapour.plugins.user = {{'tpope/vim-fugitive'}}
```
