### ISSUE TITLE
How to override plugin config

### ISSUE THREAD

**Issue by Cyberlane** [VapourNvim/VapourNvim#53]
I would like to override the default width for the `nvim-tree` plugin within my `user-config/init.lua` file.

I have been digging in your code to try understand a way to do this, but I cannot see a way to achieve this. So currently I have to execute `:NvimTreeResize 40` manually. Maybe I am missing something, but is there a way I can override your defaults?

**Comment by hackorum** [comment]
You can add `Vapour.plugins.nvim_tree.view_width = 40` to your user config

**Comment by Cyberlane** [comment]
Thank you!
