### ISSUE TITLE
error on evert start

### ISSUE THREAD

**Issue by Aneeqasif** [VapourNvim/VapourNvim#54]
whenever i start nvim i see this
```
No C compiler found! "gcc-11" are not executable.                                                                                       
No C compiler found! "gcc-11" are not executable.                                                                                       
No C compiler found! "gcc-11" are not executable.                                                                                       
[cmp-dictionary] No such file: /usr/share/dict/words                                                                                    
Press ENTER or type command to continue       
```

how to get rid of it

**Comment by hackorum** [comment]
Thank you for using VapourNvim! To fix this error you will have to install gcc using the package manager that is available on your os. I hope it helps :)

**Comment by Aneeqasif** [comment]
![image](https://user-images.githubusercontent.com/78728701/150643007-83d747f5-52d8-4850-a5c4-44f359958358.png)
i think i all ready have it
can u point out which pakage on arch i need to install if its not here

**Comment by Aneeqasif** [comment]
> Thank you for using VapourNvim! To fix this error you will have to install gcc using the package manager that is available on your os. I hope it helps :)

can u plz tell which pakage i need specifically

**Comment by hackorum** [comment]
If you go into your terminal, are you able to run `gcc-11`

**Comment by Aneeqasif** [comment]
> If you go into your terminal, are you able to run `gcc-11`

no but i can run `gcc` just fine

**Comment by hackorum** [comment]
Try removing `~/.local/share/nvim`

**Comment by CaninoDev** [comment]
I have a similar problem upon startup even after `rm -rf ~/.local/share/nvim` but I do confirm having `gcc` installed.
`which gcc` yields `/usr/bin/gcc`
`gcc --version` yields `11.1.0`

**Comment by Aneeqasif** [comment]
> Try removing `~/.local/share/nvim`

i have again installed this updated merge but now i have this on terminal
`nvim-treesitter[phpdoc]: Error during `npm install` (required for parser generation of phpdoc with npm                                  
 dependencies)                                                                                                                          
npm WARN old lockfile                                                                                                                   
npm WARN old lockfile The package-lock.json file was created with an old version of npm,                                                
npm WARN old lockfile so supplemental metadata must be fetched from the registry.                                                       
npm WARN old lockfile                                                                                                                   
npm WARN old lockfile This is a one-time fix-up, please be patient...                                                                   
npm WARN old lockfile                                                                                                                   
npm WARN old lockfile Error: git dep preparation failed                                                                                 
npm WARN old lockfile     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/                                  
promise-spawn/index.js:64:27)                                                                                                           
npm WARN old lockfile     at ChildProcess.emit (node:events:390:28)                                                                     
npm WARN old lockfile     at maybeClose (node:internal/child_process:1062:16)                                                           
npm WARN old lockfile     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)                                    
npm WARN old lockfile  Could not fetch metadata for tree-sitter-php@git+ssh://git@github.com/tree-sitt                                  
er/tree-sitter-php.git#50c6951130d6de7f8e17dd4f60b66f29d482dde1 Error: git dep preparation failed                                       
npm WARN old lockfile     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/                                  
promise-spawn/index.js:64:27)                                                                                                           
npm WARN old lockfile     at ChildProcess.emit (node:events:390:28)                                                                     
npm WARN old lockfile     at maybeClose (node:internal/child_process:1062:16)                                                           
npm WARN old lockfile     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {                                  
npm WARN old lockfile   cmd: '/usr/bin/node',                                                                                           
npm WARN old lockfile   args: [                                                                                                         
npm WARN old lockfile     '/usr/lib/node_modules/npm/bin/npm-cli.js',                                                                   
npm WARN old lockfile     'install',                                                                                                    
npm WARN old lockfile     '--force',                                                                                                    
npm WARN old lockfile     '--cache=/home/aneeq/.npm',                                                                                   
npm WARN old lockfile     '--prefer-offline=false',                                                                                     
npm WARN old lockfile     '--prefer-online=false',                                                                                      
npm WARN old lockfile     '--offline=false',                                                                                            
npm WARN old lockfile     '--no-progress',                                                                                              
npm WARN old lockfile     '--no-save',                                                                                                  
npm WARN old lockfile     '--no-audit',                                                                                                 
npm WARN old lockfile     '--include=dev',                                                                                              
npm WARN old lockfile     '--include=peer',                 
npm WARN old lockfile     '--include=optional',                                                                                         
npm WARN old lockfile     '--no-package-lock-only',                                                                                     
npm WARN old lockfile     '--no-dry-run'                                                                                                
npm WARN old lockfile   ],                                                                                                              
npm WARN old lockfile   code: 1,                                                                                                        
npm WARN old lockfile   signal: null,                                                                                                   
npm WARN old lockfile   stdout: '\n> tree-sitter-php@0.19.0 install\n> node-gyp rebuild\n\n',                                           
npm WARN old lockfile   stderr: 'npm WARN using --force Recommended protections disabled.\n' +                                          
npm WARN old lockfile     'node:internal/modules/cjs/loader:936\n' +                                                                    
npm WARN old lockfile     '  throw err;\n' +                                                                                            
npm WARN old lockfile     '  ^\n' +                                                                                                     
npm WARN old lockfile     '\n' +                                                                                                        
npm WARN old lockfile     "Error: Cannot find module 'code-point-at'\n" +                                                               
npm WARN old lockfile     'Require stack:\n' +                                                                                          
npm WARN old lockfile     '- /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/string-width                                  
/index.js\n' +                                                                                                                          
npm WARN old lockfile     '- /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/wide-t                                  
runcate.js\n' +                                                                                                                         
npm WARN old lockfile     '- /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/render                                  
-template.js\n' +                                                                                                                       
npm WARN old lockfile     '- /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/plumbi                                  
ng.js\n' +                                                                                                                              
npm WARN old lockfile     '- /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/index.                                  
js\n' +                                                                                                                                 
npm WARN old lockfile     '- /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/npmlog/log.j                                  
s\n' +                                                                                                                                  
npm WARN old lockfile     '- /usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js\n' +                                       
npm WARN old lockfile     '- /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\n' +                                       
npm WARN old lockfile     '    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:9                                  
33:15)\n' +                                                                                                                             
npm WARN old lockfile     '    at Function.Module._load (node:internal/modules/cjs/loader:778:27)\n' +                                  
npm WARN old lockfile     '    at Module.require (node:internal/modules/cjs/loader:999:19)\n' +                                         
npm WARN old lockfile     '    at require (node:internal/modules/cjs/helpers:102:18)\n' +                                               
npm WARN old lockfile     '    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/                                  
-- More --                                                                                                                
npm WARN old lockfile     '    at Module._compile (node:internal/modules/cjs/loader:1097:14)\n' +                                       
npm WARN old lockfile     '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149                                  
:10)\n' +                                                                                                                               
npm WARN old lockfile     '    at Module.load (node:internal/modules/cjs/loader:975:32)\n' +                                            
npm WARN old lockfile     '    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n' +                                  
npm WARN old lockfile     '    at Module.require (node:internal/modules/cjs/loader:999:19) {\n' +                                       
npm WARN old lockfile     "  code: 'MODULE_NOT_FOUND',\n" +                                                                             
npm WARN old lockfile     '  requireStack: [\n' +                                                                                       
npm WARN old lockfile     "    '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/string-wi                                  
dth/index.js',\n" +                                                                                                                     
npm WARN old lockfile     "    '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/wid                                  
e-truncate.js',\n" +                                                                                                                    
npm WARN old lockfile     "    '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/ren                                  
der-template.js',\n" +                                                                                                                  
npm WARN old lockfile     "    '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/plu                                  
mbing.js',\n" +                                                                                                                         
npm WARN old lockfile     "    '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/ind                                  
ex.js',\n" +                                                                                                                            
npm WARN old lockfile     "    '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/npmlog/lo                                  
g.js',\n" +                                                                                                                             
npm WARN old lockfile     "    '/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js',\n" +                                  
npm WARN old lockfile     "    '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'\n" +                                   
npm WARN old lockfile     '  ]\n' +                                                                                                     
npm WARN old lockfile     '}\n' +                                                                                                       
npm WARN old lockfile     '\n' +                                                                                                        
npm WARN old lockfile     'Node.js v17.3.0\n' +                                                                                         
npm WARN old lockfile     'npm ERR! code 1\n' +                                                                                         
npm WARN old lockfile     'npm ERR! path /home/aneeq/.npm/_cacache/tmp/git-clone5idfPk\n' +                                             
npm WARN old lockfile     'npm ERR! command failed\n' +                                                                                 
npm WARN old lockfile     'npm ERR! command sh -c node-gyp rebuild\n' +                                                                 
npm WARN old lockfile     '\n' +                                                                                                        
npm WARN old lockfile     'npm ERR! A complete log of this run can be found in:\n' +                                                    
npm WARN old lockfile     'npm ERR!     /home/aneeq/.npm/_logs/2022-01-23T06_14_03_611Z-debug-0.log\n'      
npm WARN old lockfile }                                                                                                                 
npm notice                                                                                                                              
npm notice New patch version of npm available! 8.3.0 -> 8.3.2                                                                           
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.3.2>                                                                  
npm notice Run `npm install -g npm@8.3.2` to update!                                                                                    
npm notice                                                                                                                              
npm ERR! code 1                                                                                                                         
npm ERR! git dep preparation failed                                                                                                     
npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/                                  
aneeq/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-a                                  
udit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run                                                
npm ERR! > tree-sitter-php@0.19.0 install                                                                                               
npm ERR! > node-gyp rebuild                                                                                                             
npm ERR! npm WARN using --force Recommended protections disabled.                                                                       
npm ERR! node:internal/modules/cjs/loader:936                                                                                           
npm ERR!   throw err;                                                                                                                   
npm ERR!   ^                                                                                                                            
npm ERR!                                                                                                                                
npm ERR! Error: Cannot find module 'code-point-at'                                                                                      
npm ERR! Require stack:                                                                                                                 
npm ERR! - /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/string-width/index.js                                           
npm ERR! - /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/wide-truncate.js                                          
npm ERR! - /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/render-template.js                                        
npm ERR! - /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/plumbing.js                                               
npm ERR! - /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/index.js                                                  
npm ERR! - /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/npmlog/log.js                                                   
npm ERR! - /usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js                                                              
npm ERR! - /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js                                                              
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)                                              
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)                                                         
npm ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)                                                                
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)                                                                      
npm ERR!     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/strin              
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)                                                                      
npm ERR!     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/strin                                  
g-width/index.js:3:19)                                                                                                                  
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1097:14)                                                              
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)                                                
npm ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)                                                                   
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)                                                         
npm ERR!     at Module.require (node:internal/modules/cjs/loader:999:19) {                                                              
npm ERR!   code: 'MODULE_NOT_FOUND',                                                                                                    
npm ERR!   requireStack: [                                                                                                              
npm ERR!     '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/string-width/index.js',                                      
npm ERR!     '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/wide-truncate.js',                                     
npm ERR!     '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/render-template.js',                                   
npm ERR!     '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/plumbing.js',                                          
npm ERR!     '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/index.js',                                             
npm ERR!     '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/npmlog/log.js',                                              
npm ERR!     '/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js',                                                         
npm ERR!     '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'                                                          
npm ERR!   ]                                                                                                                            
npm ERR! }                                                                                                                              
npm ERR!                                                                                                                                
npm ERR! Node.js v17.3.0                                                                                                                
npm ERR! npm ERR! code 1                                                                                                                
npm ERR! npm ERR! path /home/aneeq/.npm/_cacache/tmp/git-clone69f4Rw                                                                    
npm ERR! npm ERR! command failed                                                                                                        
npm ERR! npm ERR! command sh -c node-gyp rebuild                                                                                        
npm ERR!                                                                                                                                
npm ERR! npm ERR! A complete log of this run can be found in:                                                                           
npm ERR! npm ERR!     /home/aneeq/.npm/_logs/2022-01-23T06_15_32_208Z-debug-0.log                                                       
npm ERR! A complete log of this run can be found in:                                                                                    
npm ERR!     /home/aneeq/.npm/_logs/2022-01-23T06_13_31_652Z-debug-0.log                  `

**Comment by Aneeqasif** [comment]
after runing packer sync this is shoeing up every time i am opening nvim
`Error executing luv callback:
...acker/start/cmp-dictionary/lua/cmp_dictionary/caches.lua:49: attempt to index a nil value
stack traceback:
        ...acker/start/cmp-dictionary/lua/cmp_dictionary/caches.lua:49: in function 'indexing'
        ...acker/start/cmp-dictionary/lua/cmp_dictionary/caches.lua:119: in function '_create_cache'
        ...acker/start/cmp-dictionary/lua/cmp_dictionary/caches.lua:130: in function 'create_cache_sync'
        ...acker/start/cmp-dictionary/lua/cmp_dictionary/caches.lua:240: in function <...acker/start/cmp-dictiona
ry/lua/cmp_dictionary/caches.lua:226>
        [C]: in function 'cmd'
        ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:139: in function <...m/site/pack/packer/start
/packer.nvim/lua/packer/load.lua:118>
        [C]: in function 'pcall'
        ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:162: in function <...m/site/pack/packer/start
/packer.nvim/lua/packer/load.lua:161>
        [string ":lua"]:1: in main chunk
`

**Comment by hackorum** [comment]
Do you use php

**Comment by Aneeqasif** [comment]
> Do you use php

mmm how

**Comment by hackorum** [comment]
Ok then you can press space+E and then add this line in the file:
Vapour.plugins.treesitter.ignore_install = {'phpdoc'}
