### ISSUE TITLE
Errors when pressing tab

### ISSUE THREAD

**Issue by logicguy1** [VapourNvim/VapourNvim#56]
Hey! First of id like to say that this is such a cool projct :p big fan :star: from me :D 

Now to cut the chase im getting some annoying errors when pressing tab, not exactly sure why
![image](https://user-images.githubusercontent.com/56993729/151357711-4bc108bf-e3be-46d9-a315-b74f7718e28a.png)
I did install all the requrements and they are up to date

I use arch, btw

If you need anything else tell me

**Comment by hackorum** [comment]
Glad you liked VapourNvim :)

Sorry, I had one line commented out in the plugins file. Now I have fixed it in the latest commit. I hope it fixes the issue for you too.

**Comment by logicguy1** [comment]
Perfect thank you :D
