### ISSUE TITLE
Color scheme partially stuck as rose-pine

### ISSUE THREAD

**Issue by threedope** [VapourNvim/VapourNvim#63]
Tested on multiple color schemes by adding to vapour/user-config/init.lua
`Vapour.settings.colorscheme =  'not-rose-pine'`

And alternatively by changing the settings in vapour/init.lua to
`colorscheme = 'not-rose-pine'`
`lualine-colorscheme = 'not-rose-pine'`

Screenshots below are with gruvbox selected, where the inactive buffer indicator and bottom lualine bar have improper theming.
OS is Arch Linux w/ Gnome Terminal.

![Screenshot from 2022-02-07 12-15-57](https://user-images.githubusercontent.com/55446805/152857551-903eac61-16de-4299-97a0-38cec3593c20.png)
![Screenshot from 2022-02-07 12-25-03](https://user-images.githubusercontent.com/55446805/152857563-1412c010-3211-4ca3-8c54-24f6c0041679.png)

**Comment by hackorum** [comment]
Sorry, I haven't been very active for a long time because I have exams. I have fixed this in the latest commit. You do not need to change lualine_colorscheme anymore. It will automatically take it based on your current colorscheme.
